services:
    mariadb:
        container_name: "mariadb"
        image: mariadb:10.9.5
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db_forex
            MYSQL_USER: forex_user
            MYSQL_PASSWORD: forex_password
        volumes:
            - "./database/scripts:/docker-entrypoint-initdb.d"

    server:
        container_name: "server"
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            - mariadb
        env_file:
            - .env
