CREATE OR REPLACE DATABASE db_forex;
USE db_forex;

CREATE OR REPLACE TABLE eurusd(
    id INT PRIMARY KEY AUTO_INCREMENT,
    symbol CHAR(6) NOT NULL,
    datetime DATETIME NOT NULL,
    ask DOUBLE NOT NULL,
    bid DOUBLE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NULL
)